config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'categories#index'
  resources :categories, :activities

end

app/models/activity.rb
class Activity < ActiveRecord::Base
 belongs_to :category
 paginates_per 6
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, uniqueness: true
  has_many :activities
  paginates_per 4

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def show
    @activity = Activity.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  require 'open-uri'
  require 'json'

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @activities = Activity.where(category_id: @category.id).page params[:page]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/show.html.erb
<div class="row">
  <div class="large-12 columns">
    <%= link_to "Back", category_path(@activity.category_id ), class: "small radius button back button-activities" %>
    <div class="hide-for-small">
      <div id="featured">
        <!--img src="http://placehold.it/1000x400&text=Slide Image" alt="slide image"-->
        <%= image_tag @activity.img_url, style: "width:1000px;height:400px" %>
      </div>
    </div>
    <div class="row">
      <div class="small-12 show-for-small"><br>
        <!--img src="http://placehold.it/1000x600&text=For Small Screens"/-->
        <%= image_tag @activity.img_url, style: "padding:28px; margin-top:10px;width:1000px;height:300px" %>
      </div>
    </div>
  </div>
</div><br>

<div class="row">
  <div class="large-12 columns">
    <div class="row">
      <div class="large-8 columns">
        <div class="panel radius panel-border">
          <div class="row">
            <div class="large-9 small-6 columns">
              <h4><%= @activity.name %></h4><hr/>
              <p style="text-align: justify;"><%= @activity.description.truncate(200) %></p>
              <%if @activity.description.length > 200 %>
                <a id="read-more" href="#">Leer mas ...</a>
                <a id="read-less" style="display:none" href="#">Leer menos</a>
              <%end%>
              <hr>
              <div class="panel" style="border-radius: 4px;border-color: rgb(170, 146, 19);">
                <h4 style="text-decoration: underline;">Telefono:</h4>
                <p style="padding-left: 15px;"><%= @activity.phone.nil? ?  "No se ha registrado" : @activity.phone %></p>
              </div>
              <div class="show-for-small" align="center">
                <a href="#" class="small radius button website-button button-activities">Website</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="large-4 columns hide-for-small">
        <h4>More info!</h4><hr/>
        <a class="large button expand" href="#">
          Website
        </a>
        <%= link_to "<- Back", category_path(@activity.category_id ), class: "large button expand" %>
      </div>
    </div>
  </div>
</div>
<script>
  $("#read-more").on("click", function(e){
    e.preventDefault();
    $(this).hide();
    $(this).prev().text("<%= @activity.description%>");
    $(this).next().show();
  });
  $("#read-less").on("click", function(e){
    e.preventDefault();
    $(this).hide();
    $(this).prev().prev().text("<%=@activity.description.truncate(200)%>");
    $("#read-less").prev().show();
  });
</script>

app/views/categories/index.html.erb
<div id="index" class="row" style="margin-top:25%">
  <div class="large-12 columns">
    <% @categories.order('name ASC').each do |category|%>
      <div class="large-4 small-4 columns category">
        <%= link_to image_tag(category.url, class:'category circule-button'), category_path(category), class:"animated rotateIn", style:"width:100%;" %>
        <div style="margin: 10px 0">
          <%= link_to category.name, category_path(category), class:'', style:'width: 140px; border-radius: 60px; font-size: 0.8em; padding: 3px 9px; background: white'  %> </h3>
      </div>
    </div>
  <%end%>
</div>

app/views/categories/show.html.erb
<% if !@activities.empty? %>
  <div class="large-8-centered columns" style ="margin-top:50px">
    <% @activities.each do |activity| %>
      <div class="row">
        <%= link_to(activity_path(activity.id)) do %>
          <div class="small-12 columns panel" style="box-shadow: 5px 5px 25px rgb(121, 121, 121); padding-right: 0px; padding-left: 0px; margin-bottom: 15px;">
            <div class="small-4 columns">
              <% if !activity.img_url.present? %>
                <img src='http://placehold.it/1000x1000&text=Thumbnail'/>
              <%else%>
                <%= image_tag(activity.img_url, style:"solid;box-shadow: 2px 2px 3px #ACACAC;") %>
              <%end%>
            </div>
            <div class="small-8 columns">
              <h5 style="font-size: 0.8em"><%= activity.name.truncate(100) %></h5>
              <h5 style="font-size: 0.8em">Horario: L-V 8:00am - 5:00pm</h5>
            </div>
          </div>
        <%end%>
      </div>
    <%end%>
  </div>
<%end%>

<%= link_to "Back", root_path, class: "small radius button back button-activities" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DisCoveR</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script src="assets/jquery.js"></script>
    <script src="assets/foundation.js"></script>
    <script src="assets/foundation.topbar.js"></script>
    <link rel="stylesheet" href="assets/animate.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>
  <body>
    <nav class="top-bar" style="background: none" data-topbar>
    <ul class="title-area">

      <li class="name" style="background: rgba(138, 163, 38, 0.6);">
      <h1>
        <a href="../" class="hide-for-small">
          <%= image_tag "discover.png", id:'icon-header' %>
          disCoveR
        </a>
      </h1>
      </li>
    </ul>
    </nav>

    <div class="row">
      <div class="large-12 columns" style="text-align:center;position:fixed;z-index:100;top:3px;left:0;right:0">
        <h1 style="font-family: titleFont;color: white; letter-spacing: 3px; font-size: 25px">disCoveR</span></h1>
      </div>
    </div>


    <div style="height:100%; overflow: scroll">
      <%= yield %>
    </div>
    <script>
      $(document).foundation();
    </script>
  </body>
</html>